# https://github.com/WSukmas/Workshop_ECPRL/blob/main/bandgaps_ABC3.ipynb

In [16]:
!pip install mp-api --user

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple


In [18]:
from matminer.data_retrieval.retrieve_MP import MPDataRetrieval
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifParser
import matminer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%config InlineBackend.figure_format='retina'
%matplotlib Inline

In [2]:
# mp-1207450: Zn9Fe4 (cubic, I-43m, 217) https://legacy.materialsproject.org/materials/mp-1207450/

from pymatgen.io.cif import CifParser

mpr = MPRester("foqWelVbBoixU9suS6DAz6xg7RASqTVq")

material_ID = "mp-1207450"
structure = mpr.get_data(material_ID, data_type='', prop='cif').get("cif")

In [3]:
parser = CifParser.from_string(structure)

In [4]:
structure = parser.get_structures()
print(structure[0])

Full Formula (Zn18 Fe8)
Reduced Formula: Zn9Fe4
abc   :   7.773250   7.773250   7.773250
angles: 109.471221 109.471221 109.471221
Sites (26)
  #  SP           a         b         c
---  ----  --------  --------  --------
  0  Fe    0.793479  0         0
  1  Fe    1         0.793479  1
  2  Fe    1         0         0.793479
  3  Fe    0.206521  0.206521  0.206521
  4  Fe    0.316661  0         0
  5  Fe    1         0.316661  1
  6  Fe    1         1         0.316661
  7  Fe    0.683339  0.683339  0.683339
  8  Zn    0.643763  0.248717  0
  9  Zn    0.248717  0.643763  1
 10  Zn    0.751283  0.751283  0.395046
 11  Zn    0.395046  0.751283  0.751283
 12  Zn    0.356237  0.356237  0.604954
 13  Zn    0.604954  0.356237  0.356237
 14  Zn    1         0.643763  0.248717
 15  Zn    1         0.248717  0.643763
 16  Zn    0.643763  0         0.248717
 17  Zn    0.356237  0.604954  0.356237
 18  Zn    0.751283  0.395046  0.751283
 19  Zn    0.248717  0         0.643763
 20  Zn    0         

In [5]:
Zn9Fe4 = structure[0]

print(Zn9Fe4.lattice)
print(Zn9Fe4.species)
print(Zn9Fe4.charge)
print(Zn9Fe4.cart_coords)
print(Zn9Fe4.atomic_numbers)

4.487888 4.487888 4.487888
4.487888 -4.487888 -4.487888
-4.487888 4.487888 -4.487888
[Element Fe, Element Fe, Element Fe, Element Fe, Element Fe, Element Fe, Element Fe, Element Fe, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn, Element Zn]
0.0
[[ 3.56104488e+00  3.56104488e+00  3.56104488e+00]
 [ 3.56104488e+00  5.41473112e+00 -3.56104488e+00]
 [ 9.26843118e-01  8.04893288e+00  9.26843118e-01]
 [ 9.26843118e-01  9.26843118e-01 -9.26843118e-01]
 [ 1.42113910e+00  1.42113910e+00  1.42113910e+00]
 [ 1.42113910e+00  7.55463690e+00 -1.42113910e+00]
 [ 7.55463690e+00  1.42113910e+00 -1.42113910e+00]
 [ 3.06674890e+00  3.06674890e+00 -3.06674890e+00]
 [ 4.00535028e+00  1.77292220e+00  1.77292220e+00]
 [-4.82537718e-01  2.71496580e+00 -6.26081020e+00]
 [ 4.97042572e+00  1.77292220e+00 -1.77292220e+00]
 [ 1.77292220e+00  1.77292220e+00 -4.

In [6]:
Zn9Fe4.species

[Element Fe,
 Element Fe,
 Element Fe,
 Element Fe,
 Element Fe,
 Element Fe,
 Element Fe,
 Element Fe,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn,
 Element Zn]

In [25]:
mean_atomic_number = np.mean(Zn9Fe4.atomic_numbers)
max_atomic_number = np.max(Zn9Fe4.atomic_numbers)
min_atomic_number = np.min(Zn9Fe4.atomic_numbers)
std_atomic_number = np.std(Zn9Fe4.atomic_numbers)

print(mean_atomic_number, max_atomic_number, min_atomic_number, std_atomic_number)

28.76923076923077 30 26 1.8461538461538463


In [26]:
mean_distance_matrix = np.mean(Zn9Fe4.distance_matrix)
max_distance_matrix = np.max(Zn9Fe4.distance_matrix)
min_distance_matrix = np.min(Zn9Fe4.distance_matrix)
std_distance_matrix = np.std(Zn9Fe4.distance_matrix)

print(mean_distance_matrix, max_distance_matrix, min_distance_matrix, std_distance_matrix)

3.34447258069263 4.681456073454327 0.0 1.0238412641887145


In [27]:
results = mpr.query({"formula_anonymous": "ABC3"}, properties=["cif", "band_gap"])

MPRestError: REST query returned with error status code 403. Content: b'{"valid_response": false, "error": "API_KEY is not a valid key.", "version": {"db": "2020_09_08", "pymatgen": "2022.0.8", "rest": "2.0"}, "created_at": "2022-10-25T21:26:06.626045"}'